title: "Books by Yoela O."
description:
baseurl: "/books"
url: "https://aspiring-writer.github.io"

author: Yoela Olson
social:
  github: Aspiring-Writer

# Theme Settings
logo: /books/img/logo.svg
rss: "/feed.xml"

theme_setting:
  slides_count: 5
  # blog_page: ""
  about_page: "about.md"
  archive_page: "archive.md"
  nav_pages:
    - "about.md"
    -
      title: "My Blog"
      url: "https://aspiring-writer.github.io"
    -
      title: "Writing Buddies"
      url: "https://writing-buddies.netlify.app"

code: true
math: true
mermaid: true

lang:
  category_all: All #The first tag in the categories bar on the blog layout page. By clicking it all of your posts will be shown. Default is 'All'.
  blog_title: Home
  
head_code: |
  <!-- Extra codes in the head of your site pages. You can add your Google Analysis codes here! -->


# Build Settings
theme: jekyll-theme-persephone
plugins:
  - jekyll-books
  - jekyll-sitemap

include:
  - _books
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
